/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PantallasAdministrador;

import DAO.DAORecepcionistaImplements;
import Informacion.Usuario;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Jhon SM
 */
public class PanelModificarRecepcionista extends javax.swing.JPanel {

    DAORecepcionistaImplements Re=new DAORecepcionistaImplements();
    Usuario usu=new Usuario();
    
    public PanelModificarRecepcionista() {
        initComponents();
        Re.CargarTablaRecepcionista(JtableRecepcionista);
        Listener();
        
    }

    
    public void Listener(){
        // Agregar listener a la tabla para capturar selecciones de fila
        JtableRecepcionista.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = JtableRecepcionista.getSelectedRow();
                    if (selectedRow != -1) {
                        // Obtener el ID de usuario de la fila seleccionada
                        int idUsuario = (int) JtableRecepcionista.getValueAt(selectedRow, 0);
                        usu.setId_usuario(idUsuario);
                        
                        // Llamar al método para obtener información del usuario por su ID
                        Re.obtenerInformacionRecepcionista(usu);
                        
                        // Mostrar la información del usuario en los campos de texto
                        if (usu != null) {
                            txtUsuario.setText(usu.getNombre_usuario());
                            txtcontra.setText(usu.getClave_usuario());
                            txtnombres.setText(usu.getNombres_usu());
                            txtapepater.setText(usu.getApellidoPaterno_usu());
                            txtapemater.setText(usu.getApellidoMaterno_usu());
                            txtdirec.setText(usu.getDireccion_usu());
                            txttelef.setText(usu.getTelefono_usu());
                            txtcorreo.setText(usu.getCorreo_usu());
                        } 
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtapemater = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txttelef = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtcontra = new javax.swing.JTextField();
        txtapepater = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableRecepcionista = new javax.swing.JTable();
        jLabelfondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(19, 56, 235));
        jTextField2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 21)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("  Modificar Recepcionistas");
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        jTextField2.setRequestFocusEnabled(false);
        jTextField2.setVerifyInputWhenFocusTarget(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1080, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE DE USUARIO:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("APELLIDO PATERNO:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NOMBRES:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoAUR.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIRECCION:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELEFONO:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CORREO:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Recepcionista");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ROL:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("APELLIDO MATERNO:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        txtapemater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapematerActionPerformed(evt);
            }
        });
        add(txtapemater, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 220, 30));
        add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 220, 30));
        add(txttelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 220, 30));

        txtdirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirecActionPerformed(evt);
            }
        });
        add(txtdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 220, 30));
        add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 220, 30));
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 220, 30));

        txtcontra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 220, 30));
        add(txtapepater, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 220, 30));

        btnActualizar.setBackground(new java.awt.Color(102, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Modificar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 170, 43));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondocrear.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 580, 507));
        jLabel7.getAccessibleContext().setAccessibleName("");

        JtableRecepcionista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID usuario", "Nombre de Usuario", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(JtableRecepcionista);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 450, 450));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPaneles.jpg"))); // NOI18N
        add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtdirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdirecActionPerformed

    private void txtapematerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapematerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapematerActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Actualizar el objeto Usuario con los nuevos valores
                usu.setNombre_usuario(txtUsuario.getText());
                usu.setClave_usuario(txtcontra.getText());
                usu.setNombres_usu(txtnombres.getText());
                usu.setApellidoPaterno_usu(txtapepater.getText());
                usu.setApellidoMaterno_usu(txtapemater.getText());
                usu.setDireccion_usu(txtdirec.getText());
                usu.setTelefono_usu(txttelef.getText());
                usu.setCorreo_usu(txtcorreo.getText());
                
                // Llamar al método para actualizar en la base de datos
                boolean actualizado = Re.actualizarRecepcionista(usu);
                
                if (actualizado) {
                    JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente.");
                     Re.CargarTablaRecepcionista(JtableRecepcionista);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar usuario,revise si selecciono una fila");
                }
                
        
    }//GEN-LAST:event_btnActualizarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableRecepcionista;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtapemater;
    private javax.swing.JTextField txtapepater;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelef;
    // End of variables declaration//GEN-END:variables
}
