/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PantallasGenerales;

import PantallasRecepcionista.PanelAlquilarEquipos;
import Informacion.Usuario;
import PantallasAdministrador.PanelAdministrarEstadoEquipos;
import PantallasAdministrador.PanelAgregarEquipo;
import PantallasAdministrador.PanelModificarRecepcionista;
import PantallasAdministrador.PanelModificarCliente;
import PantallasAdministrador.PanelRegistrarRecepcionista;
import PantallasRecepcionista.PanelComprobantePago;
import PantallasRecepcionista.PanelListarClientes;
import PantallasRecepcionista.PanelListarEquipos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrador
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Usuario usu;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        usu = usuario;
        Lbl_NombreUsuario.setText(usuario.getNombre_usuario());
        Lbl_Correo.setText(String.valueOf(usuario.getCorreo_usu()));
        Lbl_NomApe.setText(usuario.getNombres_usu() + " " + usuario.getApellidoPaterno_usu());
        cambiarNombreBotones();

    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1060, 720);
        j.setLocation(0, 0);

        PnlBase.removeAll();
        PnlBase.add(j, BorderLayout.CENTER);
        PnlBase.revalidate();
        PnlBase.repaint();

    }

    private void cambiarNombreBotones() {
        if ("recepcionista".equals(usu.getNombre_rol())) {
            jButton1.setText("COMPROBANTE PAGO");
            jButton2.setText("CLIENTES");
            jButton3.setText("EQUIPOS");
            jButton4.setText("ALQUILAR EQUIPO");
            jButton5.setText("REGISTRAR CLIENTE");

            jButton1.setBackground(new Color(10,31,137));
            jButton2.setBackground(new Color(10,31,137)); 
            jButton3.setBackground(new Color(10,31,137)); 
            jButton4.setBackground(new Color(10,31,137));
            jButton5.setBackground(new Color(10,31,137));

            FondoMenu.setIcon(new ImageIcon(getClass().getResource("/img/Fondo-MenuPrincipal.jpg")));
            FondoOpciones.setIcon(new ImageIcon(getClass().getResource("/img/panelOpciones-Administrador.jpg")));
            bttn_cerrarSesion.setIcon(new ImageIcon(getClass().getResource("/img/Cerrar-Sesion-Administrador.jpg")));
            ImagenUsuario.setIcon(new ImageIcon(getClass().getResource("/img/Usuario-Administrador.png")));
            

        } else if ("administrador".equals(usu.getNombre_rol())) {
            jButton1.setText("COMPROBANTE PAGO");
            jButton2.setText("AGREGAR EQUIPO");
            jButton3.setText("MODIFICAR CLIENTE");
            jButton4.setText("ADMINISTRAR RECEPCIONISTA");
            jButton5.setText("REGISTRAR RECEPCIONISTA");

            jButton1.setBackground(new Color(10,31,137));
            jButton2.setBackground(new Color(10,31,137)); 
            jButton3.setBackground(new Color(10,31,137)); 
            jButton4.setBackground(new Color(10,31,137)); 
            jButton5.setBackground(new Color(10,31,137)); 

            FondoMenu.setIcon(new ImageIcon(getClass().getResource("/img/Fondo-MenuPrincipal-Administrador.jpg")));
            FondoOpciones.setIcon(new ImageIcon(getClass().getResource("/img/panelOpciones-Administrador.jpg")));
            bttn_cerrarSesion.setIcon(new ImageIcon(getClass().getResource("/img/Cerrar-Sesion-Administrador.jpg")));
            ImagenUsuario.setIcon(new ImageIcon(getClass().getResource("/img/Usuario-Administrador.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Lbl_NomApe = new javax.swing.JLabel();
        Lbl_NombreUsuario = new javax.swing.JLabel();
        ImagenUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_Correo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bttn_cerrarSesion = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        FondoOpciones = new javax.swing.JLabel();
        PnlFondo = new javax.swing.JPanel();
        PnlBase = new javax.swing.JPanel();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_NomApe.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        Lbl_NomApe.setForeground(java.awt.Color.white);
        Lbl_NomApe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_NomApe.setText("-");
        jPanel2.add(Lbl_NomApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 180, 20));

        Lbl_NombreUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        Lbl_NombreUsuario.setForeground(java.awt.Color.white);
        Lbl_NombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_NombreUsuario.setText("-");
        jPanel2.add(Lbl_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 180, 20));

        ImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario-Recepcionista.png"))); // NOI18N
        ImagenUsuario.setText("jLabel2");
        jPanel2.add(ImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 160, 160));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("SISTEMA DE ALQUILER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 50));

        Lbl_Correo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        Lbl_Correo.setForeground(java.awt.Color.white);
        Lbl_Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Correo.setText("-");
        jPanel2.add(Lbl_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 180, 20));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OPCION 1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 80));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("OPCION 2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 80));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OPCION 3");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 80));

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("OPCION 4");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 80));

        bttn_cerrarSesion.setBackground(new java.awt.Color(153, 0, 0));
        bttn_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cerrar-Sesion.jpg"))); // NOI18N
        bttn_cerrarSesion.setText("jButton5");
        bttn_cerrarSesion.setBorder(null);
        bttn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_cerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(bttn_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 220, 30));

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("OPCION 5");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 80));

        FondoOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelOpciones.jpg"))); // NOI18N
        FondoOpciones.setText("jLabel2");
        jPanel2.add(FondoOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        PnlFondo.setBackground(new java.awt.Color(255, 255, 0));
        PnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlBase.setOpaque(false);

        javax.swing.GroupLayout PnlBaseLayout = new javax.swing.GroupLayout(PnlBase);
        PnlBase.setLayout(PnlBaseLayout);
        PnlBaseLayout.setHorizontalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        PnlBaseLayout.setVerticalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        PnlFondo.add(PnlBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo-MenuPrincipal.jpg"))); // NOI18N
        FondoMenu.setFocusable(false);
        FondoMenu.setOpaque(true);
        PnlFondo.add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_cerrarSesionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Quieres cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            Login L = new Login();
            L.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_bttn_cerrarSesionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PanelComprobantePago pCP = new PanelComprobantePago();
        mostrarTipo(pCP);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jButton2.getText().equals("CLIENTES")) {
            PanelListarClientes pLC = new PanelListarClientes();
            mostrarTipo(pLC);
        } else if (jButton2.getText().equals("AGREGAR EQUIPO")) {
            PanelAgregarEquipo pAE = new PanelAgregarEquipo();
            mostrarTipo(pAE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jButton3.getText().equals("EQUIPOS")) {
            PanelListarEquipos pLE = new PanelListarEquipos();
            mostrarTipo(pLE);
        } else if (jButton3.getText().equals("MODIFICAR CLIENTE")) {
            PanelModificarCliente pMC = new PanelModificarCliente();
            mostrarTipo(pMC);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jButton4.getText().equals("ADMINISTRAR RECEPCIONISTA")) {
            PanelModificarRecepcionista pAR = new PanelModificarRecepcionista();
            mostrarTipo(pAR);
        } else if (jButton4.getText().equals("ALQUILAR EQUIPO")) {
            PanelAlquilarEquipos pAE = new PanelAlquilarEquipos(usu);
            mostrarTipo(pAE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jButton5.getText().equals("REGISTRAR CLIENTE")) {
            PanelRegistrarCliente pRc = new PanelRegistrarCliente();
            mostrarTipo(pRc);
        } else if (jButton5.getText().equals("REGISTRAR RECEPCIONISTA")) {
            PanelRegistrarRecepcionista pRr = new PanelRegistrarRecepcionista();
            mostrarTipo(pRr);
        }
  
    }//GEN-LAST:event_jButton5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JLabel FondoOpciones;
    private javax.swing.JLabel ImagenUsuario;
    private javax.swing.JLabel Lbl_Correo;
    private javax.swing.JLabel Lbl_NomApe;
    private javax.swing.JLabel Lbl_NombreUsuario;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PnlBase;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JButton bttn_cerrarSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
